# Generated by Django 5.1.5 on 2025-02-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='email2',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
