# Generated by Django 5.1.5 on 2025-02-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='email2',
        ),
    ]
